### PR TITLE
Added configurable timeout delay

### PR DESCRIPTION
**Pull request by emericklaw**
I have never experienced issues with duplicate button presses being detected by my buttons so have always run with a very low delay. I am currently running with 0 seconds with no issues and can press different buttons in quick succession and they all trigger.

### CODE REVIEW

**Comment by danimtb** [comment]
Thanks for the contribution!
I think I saw you message in the Hassio forum but I couldnt answer you.

Anyway, I think it is nice to let users choose whatever delay suits theis setup, as this would be very dependant on things suchs the router, the latency of their LAN and even the amount of devices connected to it.

I would just change the merge branch to develop and see if I we can release a new version soon.

**Comment by emericklaw** [comment]
Ah, it was not me on the forums but I did also see that there are at least two other forks where people have manually changed the timeout to a lower value for their own use.

My Home Assistant install is currently pointing to my repo so no immediate need to release a new version.

**Comment by mattlward** [comment]
Does this mean that this is going to happen in the next release?  I did ask about it on the homeassistant forum.  

Thanks

**Comment by danimtb** [comment]
Merging this to develop! Thank you @emericklaw again for the contribution! 😄

**Pull request merged**
