### PR TITLE
Update dasshio.py

### PR DESCRIPTION
**Pull request by iMarkus**

### CODE REVIEW

**Comment by danimtb** [comment]
Hi @iMarkus,

Thank you for the PR. However the guard will be removed in next version, so it is no longer needed

**Comment by iMarkus** [comment]
Alright, when will the new version be released?

**Comment by danimtb** [comment]
working on it right now

**Comment by iMarkus** [comment]
perfect, happy coding 👍

**Comment by danimtb** [comment]
New version just released. Check it out and update! :D

**Comment by iMarkus** [comment]
Works like a charm! Thanks 🥇

**Pull request closed without merging**
